### ISSUE TITLE
Make changes needed for Population Characteristics

### ISSUE THREAD

**Issue by rbiswas4** [rbiswas4/VarPop#38]
- [x] change the line of code
- [x] Add tests (#39)
- [ ] change this in `SNPop`
- [ ] Ensure examples work
